### ISSUE TITLE
Allow commands through handle ping

### ISSUE THREAD

**Issue by HalosGhost** [meskarune/autobot#8]
Some IRC bots allow commands to be read not only when they have the trigger character present at the beginning of the line, but also when the command is addressed to the bot itsefl. E.g.:

```irc
<halosghost> phrik: ❤
<phrik> I LOVE YOU TOO!❤
```

This allows for ~~incredibly, undeniably lazy~~efficient people to avoid having to reach on the keyboard for the trigger character (e.g., ``!`` is commona and even requires Shift!).

**Comment by meskarune** [comment]
Its done! \o/

**Comment by HalosGhost** [comment]
:D
